[package]
name = "doomarkable"
version = "0.3.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
doomgeneric = { git = "https://github.com/LinusCDE/doomgeneric-rs.git", tag = "0.3.0-beta.1" }
libremarkable = "0.5.0"
once_cell = "1"
fxhash = "0.2.1"
mimalloc = { version = "0.1.17", default-features = false }
log = "0.4"
env_logger = "0.9"

#core_simd = { git = "https://github.com/rust-lang/portable-simd.git", rev = "721164247cd609d04dc8f0bb2483bde83f2a7fd6" }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
